---

- ansible.builtin.include_tasks: precheck.yml  # noqa: name[missing]
  when: 'rke2_server != "" or rke2_token != ""'

- name: Ensure epel-release is installed for non-RHEL distributions
  ansible.builtin.package:
    name: 'epel-release'
  when: 'ansible_distribution != "RedHat"'

- ansible.builtin.import_tasks: firewall.yml  # noqa: name[missing]
  when: 'rke2_configure_firewall | bool'

- name: Ensure NetworkManager is configured for canal
  ansible.builtin.copy:
    src: 'etc/NetworkManager/conf.d/rke2-canal.conf'
    dest: '/etc/NetworkManager/conf.d/rke2-canal.conf'
    mode: '0644'
    owner: 'root'
    group: 'root'
  notify: 'Restart NetworkManager'

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Ensure rancher repository configuration exists
  ansible.builtin.template:
    src: 'etc/yum.repos.d/rancher.repo.j2'
    dest: '/etc/yum.repos.d/rancher.repo'
    mode: '0644'
    owner: 'root'
    group: 'root'

- name: Ensure rke2 is installed
  ansible.builtin.dnf:
    name: 'rke2-{{ rke2_mode }}'
    update_cache: true

- name: Ensure rke2 configuration exists
  ansible.builtin.template:
    src: 'etc/rancher/rke2/config.yaml.j2'
    dest: '/etc/rancher/rke2/config.yaml'
    mode: '0600'
    owner: 'root'
    group: 'root'
  notify: '{{ "Restart " ~ ("rke2-server" if rke2_mode == "server" else "rke2-agent") }}'

- name: Ensure rke2 is enabled and running
  ansible.builtin.service:
    name: 'rke2-{{ rke2_mode }}'
    enabled: true
    state: 'started'

- ansible.builtin.include_tasks: server.yml  # noqa: name[missing]
  when: 'rke2_mode == "server"'
