---

- name: Assert supported operating system distribution
  ansible.builtin.assert:
    that: 'ansible_os_family == "RedHat"'
    quiet: true
    fail_msg: 'Unsupported OS distribution: {{ ansible_os_family }}'

- name: Assert that agent required variables are set
  ansible.builtin.assert:
    that: '{{ item }} | length > 0'
    quiet: true
    fail_msg: '{{ item }} is not defined for agent.'
  loop:
    - 'rke2_token'
    - 'rke2_server'
